#!/bin/bash
ubuntu-vm-builder kvm precise \
                  --domain rmubusvr05 \
                  --dest newvm \
                  --arch i386 \
                  --hostname rmubusvr05 \
                  --mem 256 \
                  --user rmay \
                  --pass test \
                  --ip 192.168.120.98 \
                  --mask 255.255.255.0 \
                  --net 192.168.120.0 \
                  --bcast 192.168.120.255 \
                  --gw 192.168.120.1 \
                  --dns 192.168.120.1 \
                  --mirror http://archive.localubuntumirror.net/ubuntu \
                  --components main,universe \
                  --addpkg acpid \ 
                  --addpkg openssh-server \
                  --addpkg avahi-daemon \
                  --libvirt qemu:///system ;
